In [1]:
import pandas as pd
df=pd.read_csv("E-Commerce Sales Analytics.csv")
df.head(10)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
5,10006,1/6/2022,1071,Electronics,West,2,264.44,0.20,Card,3,3.3,423.10
6,10007,1/7/2022,1700,Clothing,South,6,564.60,0.23,Card,1,1.8,2608.45
7,10008,1/8/2022,1020,Beauty,North,6,265.71,0.13,Card,2,3.7,1387.01
8,10009,1/9/2022,1614,Clothing,South,6,224.65,0.27,Card,2,1.4,983.97
9,10010,1/10/2022,1121,Clothing,West,4,272.71,0.06,Card,10,4.5,1025.39

In [2]:
df.tail(10)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
4990,14991,8/31/2035,1012,Home,East,1,265.48,0.32,Card,10,2.9,180.53
4991,14992,9/1/2035,1183,Home,North,2,353.46,0.28,COD,9,4.9,508.98
4992,14993,9/2/2035,1110,Home,North,2,285.82,0.03,Wallet,11,4.9,554.49
4993,14994,9/3/2035,1926,Electronics,West,1,113.63,0.14,COD,4,1.0,97.72
4994,14995,9/4/2035,1507,Home,South,6,25.85,0.12,Card,5,3.1,136.49
4995,14996,9/5/2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,9/6/2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,9/7/2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,9/8/2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,9/9/2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [3]:
df.shape

(5000, 12)

In [4]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   object
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 468.9+ KB

In [6]:
df.describe()

,order_id,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
std,1443.520003,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219
min,10001.000000,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000

In [7]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.dtypes

order_id              int64
order_date           object
customer_id           int64
product_category     object
region               object
quantity              int64
unit_price          float64
discount            float64
payment_method       object
delivery_days         int64
customer_rating     float64
revenue             float64
dtype: object

In [10]:
df["order_date"] = pd.to_datetime(df["order_date"])
df.dtypes

order_id                     int64
order_date          datetime64[ns]
customer_id                  int64
product_category            object
region                      object
quantity                     int64
unit_price                 float64
discount                   float64
payment_method              object
delivery_days                int64
customer_rating            float64
revenue                    float64
dtype: object

In [11]:
df["payment_method"].unique()

array(['Wallet', 'Card', 'COD'], dtype=object)

In [12]:
df["product_category"].unique()

array(['Beauty', 'Clothing', 'Electronics', 'Home'], dtype=object)

In [13]:
df["region"].unique()

array(['South', 'East', 'West', 'North'], dtype=object)

In [14]:
df["quantity"].min(),df["quantity"].max()

(1, 7)

In [15]:
df["unit_price"].min(),df["unit_price"].max()

(15.15, 599.96)

In [16]:
df["discount"].min(),df["discount"].max()

(0.0, 0.35)

In [17]:
df["delivery_days"].min(),df["delivery_days"].max()

(1, 11)

In [18]:
df["customer_rating"].min(),df["customer_rating"].max()

(1.0, 5.0)

In [19]:
df["revenue"].min(),df["revenue"].max()

(11.21, 4119.33)

In [20]:
df["order_date"].min(),df["order_date"].max()

(Timestamp('2022-01-01 00:00:00'), Timestamp('2035-09-09 00:00:00'))

In [21]:
df["Year"]=df["order_date"].dt.year
df["Month"]=df["order_date"].dt.month
df["Month_Name"]=df["order_date"].dt.month_name()

In [22]:
df[["order_date","Year","Month","Month_Name"]].head(10)

  order_date  Year  Month Month_Name
0 2022-01-01  2022      1    January
1 2022-01-02  2022      1    January
2 2022-01-03  2022      1    January
3 2022-01-04  2022      1    January
4 2022-01-05  2022      1    January
5 2022-01-06  2022      1    January
6 2022-01-07  2022      1    January
7 2022-01-08  2022      1    January
8 2022-01-09  2022      1    January
9 2022-01-10  2022      1    January

In [23]:
df["calculated_revenue"] = (
    df["quantity"] * df["unit_price"] * (1 - df["discount"])
)

In [24]:
df[["quantity", "unit_price", "discount", "revenue", "calculated_revenue"]].head(10)

   quantity  unit_price  discount  revenue  calculated_revenue
0         7      373.65      0.28  1883.20           1883.1960
1         7       47.74      0.09   304.10            304.1038
2         3      311.28      0.31   644.35            644.3496
3         5      524.47      0.02  2569.90           2569.9030
4         5      139.87      0.33   468.56            468.5645
5         2      264.44      0.20   423.10            423.1040
6         6      564.60      0.23  2608.45           2608.4520
7         6      265.71      0.13  1387.01           1387.0062
8         6      224.65      0.27   983.97            983.9670
9         4      272.71      0.06  1025.39           1025.3896

In [25]:
df["revenue_difference"] = (
    df["revenue"] - df["calculated_revenue"]
)
df["revenue_difference"].abs().max()

0.005000000000109139

In [26]:
df["calculated_revenue"] = df["calculated_revenue"].round(2)

In [27]:
df["revenue_difference"] = (
    df["revenue"] - df["calculated_revenue"]
)
df["revenue_difference"].abs().max()

0.0

In [28]:
df.drop(columns=["calculated_revenue", "revenue_difference"], inplace=True)

In [29]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue', 'Year', 'Month', 'Month_Name'],
      dtype='object')

In [30]:
df["revenue"].sum()

np.float64(5109775.74)

In [31]:
df["revenue"].mean()

np.float64(1021.955148)

In [32]:
#which product category generates the most revenue
category_sales = df.groupby("product_category")["revenue"].sum()
category_sales.sort_values(ascending=False)

product_category
Electronics    1829899.22
Clothing       1531931.72
Home            982083.92
Beauty          765860.88
Name: revenue, dtype: float64

In [33]:
#calculate the no.of orders by category
orders_by_category = df.groupby("product_category")["order_id"].count()
orders_by_category.sort_values(ascending=False)

product_category
Electronics    1777
Clothing       1531
Home            969
Beauty          723
Name: order_id, dtype: int64

In [34]:
# Average revenue by category
avg_revenue_category = df.groupby("product_category")["revenue"].mean()
avg_revenue_category.sort_values(ascending=False)

product_category
Beauty         1059.281992
Electronics    1029.768835
Home           1013.502497
Clothing       1000.608570
Name: revenue, dtype: float64

In [35]:
# calculate revenue contribution
category_revenue = df.groupby("product_category")["revenue"].sum()
category_percentage = (category_revenue / df["revenue"].sum()) * 100
category_percentage.sort_values(ascending=False)

product_category
Electronics    35.811733
Clothing       29.980410
Home           19.219707
Beauty         14.988151
Name: revenue, dtype: float64

In [36]:
# Monthly sales analysis
# How much revenue did we generate in each month
monthly_sales = df.groupby(["Year", "Month", "Month_Name"])["revenue"].sum().reset_index()
monthly_sales = monthly_sales.sort_values(["Year", "Month"])
monthly_sales
monthly_sales

     Year  Month Month_Name   revenue
0    2022      1    January  35624.89
1    2022      2   February  29908.89
2    2022      3      March  30309.28
3    2022      4      April  30781.96
4    2022      5        May  41629.24
..    ...    ...        ...       ...
160  2035      5        May  33393.87
161  2035      6       June  25205.26
162  2035      7       July  23944.48
163  2035      8     August  29354.74
164  2035      9  September   4952.23

[165 rows x 4 columns]

In [37]:
# Highest revenue month
monthly_sales.loc[monthly_sales["revenue"].idxmax()]

Year              2026
Month                8
Month_Name      August
revenue       44728.82
Name: 55, dtype: object

In [38]:
# Lowest revenue month
monthly_sales.loc[monthly_sales["revenue"].idxmin()]

Year               2035
Month                 9
Month_Name    September
revenue         4952.23
Name: 164, dtype: object

In [39]:
# Monthly avg revenue
average_monthly_revenue = monthly_sales["revenue"].mean()
round(average_monthly_revenue, 2)

np.float64(30968.34)

In [40]:
# Count orders in each month
monthly_orders = df.groupby(["Year", "Month", "Month_Name"])["order_id"].count().reset_index()
monthly_orders

     Year  Month Month_Name  order_id
0    2022      1    January        31
1    2022      2   February        28
2    2022      3      March        31
3    2022      4      April        30
4    2022      5        May        31
..    ...    ...        ...       ...
160  2035      5        May        31
161  2035      6       June        30
162  2035      7       July        31
163  2035      8     August        31
164  2035      9  September         9

[165 rows x 4 columns]

In [41]:
# Avg order value by month
monthly_aov = df.groupby(["Year", "Month", "Month_Name"])["revenue"].mean().reset_index()
monthly_aov = monthly_aov.rename(columns={"revenue": "average_order_value"})
monthly_aov

     Year  Month Month_Name  average_order_value
0    2022      1    January          1149.190000
1    2022      2   February          1068.174643
2    2022      3      March           977.718710
3    2022      4      April          1026.065333
4    2022      5        May          1342.878710
..    ...    ...        ...                  ...
160  2035      5        May          1077.221613
161  2035      6       June           840.175333
162  2035      7       July           772.402581
163  2035      8     August           946.927097
164  2035      9  September           550.247778

[165 rows x 4 columns]

In [42]:
# Monthly revenue growth
monthly_sales["revenue_growth_%"] = monthly_sales["revenue"].pct_change() * 100
monthly_sales

     Year  Month Month_Name   revenue  revenue_growth_%
0    2022      1    January  35624.89               NaN
1    2022      2   February  29908.89        -16.044962
2    2022      3      March  30309.28          1.338699
3    2022      4      April  30781.96          1.559522
4    2022      5        May  41629.24         35.239082
..    ...    ...        ...       ...               ...
160  2035      5        May  33393.87         20.172670
161  2035      6       June  25205.26        -24.521297
162  2035      7       July  23944.48         -5.002051
163  2035      8     August  29354.74         22.595020
164  2035      9  September   4952.23        -83.129709

[165 rows x 5 columns]

In [43]:
# Best month by no.of orders
monthly_orders.loc[monthly_orders["order_id"].idxmax()]

Year             2022
Month               1
Month_Name    January
order_id           31
Name: 0, dtype: object

In [44]:
# Month with highest avg
monthly_aov.loc[monthly_aov["average_order_value"].idxmax()]

Year                          2030
Month                            6
Month_Name                    June
average_order_value    1446.421667
Name: 101, dtype: object

In [45]:
# Month with highest revenue growth
monthly_sales.loc[monthly_sales["revenue_growth_%"].idxmax()]

Year                      2030
Month                        5
Month_Name                 May
revenue                41728.4
revenue_growth_%    118.451568
Name: 100, dtype: object

In [46]:
# Month with biggest revenue decline
monthly_sales.loc[monthly_sales["revenue_growth_%"].idxmin()]

Year                     2035
Month                       9
Month_Name          September
revenue               4952.23
revenue_growth_%   -83.129709
Name: 164, dtype: object

In [47]:
# Regional sales analysis
# calculate revenue by region and sort
region_revenue = df.groupby("region")["revenue"].sum().reset_index()
region_revenue = region_revenue.sort_values("revenue", ascending=False)
region_revenue

  region     revenue
3   West  1345582.16
1  North  1281508.45
2  South  1246640.90
0   East  1236044.23

In [48]:
# calculate orders by region
region_orders = df.groupby("region")["order_id"].count().reset_index()
region_orders = region_orders.sort_values("order_id", ascending=False)
region_orders

  region  order_id
3   West      1289
1  North      1276
0   East      1227
2  South      1208

In [49]:
# Avg revenue per order by region
region_aov = df.groupby("region")["revenue"].mean().reset_index()
region_aov = region_aov.rename(columns={"revenue": "average_order_value"})
region_aov = region_aov.sort_values("average_order_value", ascending=False)
region_aov

  region  average_order_value
3   West          1043.896168
2  South          1031.987500
0   East          1007.371011
1  North          1004.316967

In [50]:
# revenue contribution by region
region_revenue["revenue_percentage"] = (
    region_revenue["revenue"] / region_revenue["revenue"].sum()
) * 100
region_revenue["revenue_percentage"] = region_revenue["revenue_percentage"].round(2)
region_revenue

  region     revenue  revenue_percentage
3   West  1345582.16               26.33
1  North  1281508.45               25.08
2  South  1246640.90               24.40
0   East  1236044.23               24.19

In [51]:
# Region with highest revenue
region_revenue.loc[region_revenue["revenue"].idxmax()]

region                      West
revenue               1345582.16
revenue_percentage         26.33
Name: 3, dtype: object

In [52]:
# Region with highest no.of orders
region_orders.loc[region_orders["order_id"].idxmax()]

region      West
order_id    1289
Name: 3, dtype: object

In [53]:
# Region with highest avg
region_aov.loc[region_aov["average_order_value"].idxmax()]

region                        West
average_order_value    1043.896168
Name: 3, dtype: object

In [54]:
# Product Analysis
# Revenue by product category
category_quantity = df.groupby("product_category")["quantity"].mean().reset_index()
category_quantity = category_quantity.sort_values("quantity", ascending=False)
category_quantity

  product_category  quantity
0           Beauty  4.142462
3             Home  4.075335
1         Clothing  4.030699
2      Electronics  4.000563

In [55]:
# Total quantity slod by category
category_total_quantity = df.groupby("product_category")["quantity"].sum().reset_index()
category_total_quantity = category_total_quantity.sort_values(
    "quantity", ascending=False
)
category_total_quantity

  product_category  quantity
2      Electronics      7109
1         Clothing      6171
3             Home      3949
0           Beauty      2995

In [56]:
# Revenue by payment method
payment_revenue = df.groupby("payment_method")["revenue"].sum().reset_index()
payment_revenue = payment_revenue.sort_values("revenue", ascending=False)
payment_revenue

  payment_method     revenue
1           Card  2366248.20
0            COD  1788408.44
2         Wallet   955119.10

In [57]:
# orders by payment method
payment_orders=df.groupby("payment_method")["order_id"].count().reset_index()
payment_orders=payment_orders.sort_values("order_id", ascending=False)
payment_orders

  payment_method  order_id
1           Card      2270
0            COD      1774
2         Wallet       956

In [58]:
# Customer Analysis
# Revenue by customer
customer_revenue = df.groupby("customer_id")["revenue"].sum().reset_index()
customer_revenue = customer_revenue.sort_values("revenue", ascending=False)
customer_revenue.head(10)

     customer_id   revenue
657         1663  17680.69
944         1955  16265.15
668         1675  15036.46
273         1276  15023.71
641         1647  14894.97
794         1804  14330.98
191         1193  14151.65
825         1836  14110.78
946         1957  13956.95
727         1735  13146.25

In [59]:
# No.of orders per customer
customer_orders = df.groupby("customer_id")["order_id"].count().reset_index()
customer_orders = customer_orders.sort_values("order_id", ascending=False)
customer_orders.head(10)

     customer_id  order_id
657         1663        14
96          1098        12
110         1112        12
946         1957        12
924         1935        12
917         1928        12
663         1669        12
38          1038        12
606         1612        11
652         1658        11

In [60]:
# Identify repeat customers
repeat_customers = customer_orders[customer_orders["order_id"] > 1]
repeat_customers

     customer_id  order_id
657         1663        14
96          1098        12
110         1112        12
946         1957        12
924         1935        12
..           ...       ...
703         1711         2
707         1715         2
708         1716         2
710         1718         2
712         1720         2

[950 rows x 2 columns]

In [61]:
# Average customer rating
average_rating = df["customer_rating"].mean()
round(average_rating, 2)

np.float64(2.97)

In [62]:
# Till now completed 
# Data Cleaning
# Overall Revenue Analysis
# Product Category Analysis
# Monthly Sales Analysis
# Regional Analysis
# Payment Method Analysis
# Basic Customer Analysis

In [63]:
df.to_csv("ecommerce_cleaned.csv", index=False)

In [64]:
import os
os.path.exists("ecommerce_cleaned.csv")

True

In [65]:
import os
os.getcwd()

'C:\\Users\\HP'